## Basic numpy

In [1]:
import numpy as np

### 1. 1D-array from 0 to 9

In [2]:
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### 2. Boolean array 3x3 with all values are True

In [5]:
arr1 = np.ones((3, 3)) > 0
arr2 = np.ones((3, 3), dtype=bool)
arr3 = np.full((3, 3), fill_value=True, dtype=bool)
print(f"Arr1: {arr1} \n")
print(f"Arr2: {arr2} \n")
print(f"Arr3: {arr3} \n")

Arr1: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

Arr2: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

Arr3: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 



### 3. Show the result

In [7]:
arr = np. arange(0, 10)
print(arr[arr%2==1])

[1 3 5 7 9]


### 4. Show the result

In [8]:
arr = np.arange(0, 10)
arr[arr%2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 5. Show the result

In [9]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 6. Show the result

In [10]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 7. Show the result

In [11]:
arr1 = np.arange(10).reshape(2 , -1)
arr2 = np.repeat(1 ,10).reshape(2 , -1)
c = np.concatenate([arr1, arr2] , axis =1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### 8. Show the result

In [12]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


### 9. Show the result

In [13]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5)&(a<=10))
print("result", a[index])

result [ 6  9 10]


### 10. Show the result

In [14]:
def max_function(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(max_function, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


### 11. Show the result

In [15]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a<b, b, a))

Result [6 7 9 8 9 7 5]
